---

- hosts: all
  tasks:
  - name: Create directory for application
    become: true
    ansible.builtin.file:
      path: /opt/one-click-desktop
      state: directory
      owner: '{{ executive_username }}'
      group: '{{ executive_username }}'
      mode: '0755'

  - name: Clone Overseer module
    ansible.builtin.git:
      repo: https://github.com/one-click-desktop/overseer
      dest: /opt/one-click-desktop/overseer

#- name: Build docker container