---

- hosts: overseer
  tasks:
  - name: Create directory for application
    become: true
    ansible.builtin.file:
      path: /opt/one-click-desktop
      state: directory
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      recurse: yes

  - name: Clone Overseer module
    ansible.builtin.git:
      repo: https://github.com/one-click-desktop/overseer
      dest: /opt/one-click-desktop/overseer

  - name: Change owner of application
    become: true
    ansible.builtin.file:
      path: /opt/one-click-desktop
      state: directory
      owner: '{{ executive_user }}'
      group: '{{ executive_user }}'
      recurse: yes

#- name: Build docker container