---

# pakiety: qemu libvirt vagrant bridge-utils ansible ebtables dnsmasq
#akcje: 
# - utworzenie bridge'a (nmcli)
# - aktywacja libvirtd oraz jego wlaczenie
# - ustalenie domyslnego providera w vagrancie na libvirta
# - dodac uzytkownikow do grupy libvirt

- hosts: virtsrv
  tasks:
  - name: Install packages
    become: true
    block:

    #Libvirt require some firewall provider - ufw is guaranteed to work
    - name: Install virtualization tools
      community.general.pacman:
        name: 
          - libvirt
          - qemu
          - vagrant
          - dnsmasq
          - ufw
        state: present

    - name: Install addtional tools
      community.general.pacman:
        name: 
          - ansible
          - bridge utils
        state: present
  
  - name: Configure bridge interface
    become: true
    block:
    - name: Create bridge interface
      community.general.nmcli:
        type: bridge
        ifname: '{{ bridge_name }}'
        stp: no

    - name: Create bridge slave interface
      community.general.nmcli:
        type: bridge
        ifname: '{{ bridge_slave_interface }}'
        master: '{{ bridge_name }}'

    # it can crash network connection
    - name: Swap interfaces
      ansible.builtin.command: nmcli connection down '{{ slave_connection }}' && nmcli connection up bridge-'{{ bridge_name }}'

  - name: Enable and start libvirtd service
    become: true
    ansible.builtin.systemd:
      name: libvirtd
      state: started
      enabled: yes

  - name: Accept packets in UFW at bridged devices
    become: true
    ansible.builtin.lineinfile:
      path: /env
      line: '-I FORWARD -m physdev --physdev-is-bridged -j ACCEPT'
      insertbefore: 'COMMIT'
      state: present

  - name: Enable ufw
    become: true
    community.general.ufw:
      state: enabled

  - name: Reload ufw
    become: true
    community.general.ufw:
      state: reloaded

  - name: Update executive user
    become: true
    ansible.builtin.user:
      name: '{{ executive_username }}'
      groups: libvirt,kvm
      append: yes